### ISSUE TITLE
选不了出发地和目的地

### ISSUE THREAD

**Issue by SiMaLaoShi** [Betu-Li/Yun-Da#1]
pc端可以进入地图，移动端进不了地图

**Comment by Betu-Li** [comment]
我这边检查了一下，地图打不开应该是前端地图组件大小设置的问题，我这边修改了一下前端代码......如果是其他原因，可以追加运行信息

**Comment by SiMaLaoShi** [comment]
还有输入框这个只能输入数字，移动端可以定位了，但是还是选不了地址

**Comment by Betu-Li** [comment]
输入框类型类型问题已收到，我这边检查地址检索api调用是正确的，请确认前端js内位置服务key是否填写正确，或者提供更多的信息

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/71a31fde-3ea1-48c2-aa7d-bea735b14675">

**Comment by Betu-Li** [comment]
再次检查代码后发现接口调用正常，后端重构完成后会重写前端代码...暂时不会对原来的代码做维护
